config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'

  devise_for :users
  resources :statuses

    root 'statuses#index'

  get '/register' , to: 'devise/registration#new', as: :register


  get '/:feed', to: 'statuses#index', as: :feed

end

app/models/status.rb
class Status < ActiveRecord::Base

    belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


         
         has_many :statuses

        def full_name
            first_name + " " + last_name
        end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = current_user    
    @statuses = current_user.statuses.all
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @statuses = Status.all
    respond_with(@statuses)
  end

  def show
    respond_with(@status)
  end

  def new
    @status = current_user.statuses.new
    respond_with(@status)
  end

  def edit
  end

  def create
    @status = current_user.statuses.new(status_params)
    @status.save
      flash[:success] = "Cadastrado com sucesso" 
    respond_with(@status)
  end

  def update
    @status.update(status_params)
    respond_with(@status)
  end

  def destroy
    @status.destroy
    respond_with(@status)
  end

  private
    def set_status
      @status = Status.find(params[:id])
    end

    def status_params
      params.require(:status).permit(:name, :content, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(type)
		case type
				when :alert ,"alert-error"
				when :notice, "alert-warning"
				when :success, "alert-success"
				when :info , "alert-info"

				else " "
		end

	end			


end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper

	

end

app/views/layouts/_header.html.erb
<!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     <ul class="nav navbar-nav navbar-right">
        <li class="active">
        	<%= link_to 'Cadastre-se' , new_user_registration_path %>          
        </li>
        <li>
        	<%= link_to 'Log In', new_user_session_path %>
        </li>   
      </ul>
    </div><!-- /.navbar-collapse -->

app/views/layouts/_headerlogged.html.erb
<!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     <ul class="nav navbar-nav navbar-right">
        <li class="active">
        	<%= link_to 'Conta' , edit_user_registration_path %>          
        </li>
        <li>
        	<%= link_to 'Log Out', destroy_user_session_path , method: :delete %>
        </li>   
      </ul>
    </div><!-- /.navbar-collapse -->

app/views/layouts/_message.html.erb
<% flash.each do |type, message| %>
	<div class="alert <%=flash_class type %>">
	 <button class="close" data-dismiss="alert" aria-label="Close">&times;</button>
	 		<%= message %>
	</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treebook</title>
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>


<nav class="navbar navbar-inverse" role="navigation">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		 <a>
		 	<%= link_to 'Treebook', root_path , class: "navbar-brand" %>
		 </a>	
	</div>

		<% if user_signed_in? %>
			<%= render 'layouts/headerlogged' %>
		<% else %>
			<%= render 'layouts/header' %>
		<% end %>

  </div><!-- /.container-fluid -->
</nav>

<div class="container">

<%= render 'layouts/message' %>




<%= yield %>


</div>


</body>
</html>

app/views/profiles/show.html.erb
<h1> Profile from: <%= @user.full_name %></h1>
<hr>

<% @statuses.each do |status| %>
    <h3><%= link_to status.name , status %></h3>
    <hr>

<% end %>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<% if user_signed_in? %>

<h1>Listing statuses</h1>


  

<%= link_to 'New Status', new_status_path, class: "btn btn-primary" %>
<hr>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3">Commands</th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.name %></td>
        <td><%= status.content %></td>
        <td><%= status.user.full_name %></td>
        <td><%= link_to 'Show', status %></td>
        <td><%= link_to 'Edit', edit_status_path(status) %></td>
        <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<% end %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @status.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @status.user.full_name %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', :back %>